### ISSUE TITLE
Wireless sniffing possible?

### ISSUE THREAD

**Issue by chevalnoir1** [nccgroup/phantap#10]
Hi,

I have my setup as follows   cable ----------> router ----(wi-fi)------> devices. Is it possible to connect the ar-150 to router via ethernet cable and then set it up in range extender to sniff traffic? any other way also works.

Thanks in advance.

**Comment by Bloup1net** [comment]
Hi chevalnoir1 ,

PhanTap doesn't have any specific tools in order to sniff wireless traffic, like for example https://www.aircrack-ng.org/ does. PhanTap is the package that configures the router by sniffing ethernet packets, by taking advantage of the trust that is made to the physical access to the network.  If you extend a wireless network, you'd need first to have credentials to connect to it, and after to have users trust your AP and connect to it, which has nothing to do with PhanTap.
I hope this answers your question, I will close the ticket, please reopen it if you have any more questions.

Thanks,
Diana
